'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { Icon } from './icons';
import { DonutChart, LegendRow, MetricCard, PageHeading, PanelHeader } from './dashboard-primitives';
import { useInspections } from '../lib/inspection-store';

export function AnalysisPage() {
  const { inspections } = useInspections();
  const [city, setCity] = useState('Todas as cidades');
  const [type, setType] = useState('Todos os tipos');
  const filtered = useMemo(() => inspections.filter((item) => (city === 'Todas as cidades' || item.city.includes(city)) && (type === 'Todos os tipos' || item.type === type)), [city, inspections, type]);
  const completed = filtered.filter((item) => item.status.toLowerCase().includes('conclu')).length;
  const pending = filtered.filter((item) => item.status.toLowerCase().includes('pend') || item.status.toLowerCase().includes('agend')).length;
  const inProgress = filtered.filter((item) => item.status.toLowerCase().includes('andamento')).length;
  const total = filtered.length;
  const cities = Array.from(new Set(inspections.map((item) => item.city.split(',')[0])));
  function reset() { setCity('Todas as cidades'); setType('Todos os tipos'); }
  return <>
    <PageHeading title="Análises e indicadores" description="Acompanhe o desempenho das triagens e tome decisões com base nos dados da operação." side="Atualização em tempo real\nDados do período atual" />
    <section className="filters-bar" aria-label="Filtros de análise"><label className="filter-field"><span>Período</span><div className="filter-select"><Icon name="calendar" size={17} /><select defaultValue="Abril de 2024"><option>Abril de 2024</option><option>Março de 2024</option></select><Icon name="chevronDown" size={14} /></div></label><label className="filter-field"><span>Cidade</span><div className="filter-select"><Icon name="mapPin" size={17} /><select value={city} onChange={(event) => setCity(event.target.value)}><option>Todas as cidades</option>{cities.map((item) => <option key={item}>{item}</option>)}</select><Icon name="chevronDown" size={14} /></div></label><label className="filter-field"><span>Tipo de triagem</span><div className="filter-select"><Icon name="file" size={17} /><select value={type} onChange={(event) => setType(event.target.value)}><option>Todos os tipos</option><option>Entrada</option><option>Saída</option><option>Periódica</option></select><Icon name="chevronDown" size={14} /></div></label><label className="filter-field"><span>Equipe</span><div className="filter-select"><Icon name="users" size={17} /><select defaultValue="Todas as equipes"><option>Todas as equipes</option><option>Equipe São Paulo</option><option>Equipe ABC</option></select><Icon name="chevronDown" size={14} /></div></label><button className="filter-reset" type="button" onClick={reset}><Icon name="refresh" size={16} /> Limpar filtros</button></section>
    <section className="stats-grid"><MetricCard icon="building" label="Total de triagens" value={String(total)} trend="↗ 12%" note="no período filtrado" /><MetricCard icon="clock" label="Em andamento" value={String(inProgress)} trend="↓ 18%" trendTone="down" note="com execução iniciada" tone="blue" /><MetricCard icon="check" label="Taxa de conclusão" value={`${total ? Math.round((completed / total) * 100) : 0}%`} trend="↗ 6 p.p." note="do período filtrado" /><MetricCard icon="file" label="Aguardando execução" value={String(pending)} trend="↗ 14%" note="na fila de trabalho" tone="blue" /></section>
    <section className="analysis-grid"><article className="panel"><PanelHeader title="Triagens por status" action={<Link className="chart-select" href="/triagens">Abrir lista <Icon name="arrowRight" size={14} /></Link>} /><div className="panel-body"><DonutChart value={total ? Math.round((completed / total) * 100) : 0} label={String(total)} unit="triagens"><div className="legend"><LegendRow label="Concluídas" value={completed} percent={total ? Math.round((completed / total) * 100) : 0} color="green" /><LegendRow label="Em andamento" value={inProgress} percent={total ? Math.round((inProgress / total) * 100) : 0} color="yellow" /><LegendRow label="Aguardando" value={pending} percent={total ? Math.round((pending / total) * 100) : 0} color="orange" /></div></DonutChart></div></article><article className="panel"><PanelHeader title="Triagens por cidade" /><div className="panel-body horizontal-bars">{cities.map((item) => { const value = filtered.filter((inspection) => inspection.city.startsWith(item)).length; return <div className="hbar-row" key={item}><span>{item}</span><div className="hbar-track"><div className="hbar-fill" style={{ width: `${Math.max(value * 14, 8)}%`, background: '#07825f' }} /></div><span className="hbar-value">{value}</span></div>; })}</div></article></section>
    <section className="analysis-grid analysis-grid--bottom"><article className="panel"><PanelHeader title="Últimas triagens avaliadas" /><div className="panel-body"><table className="data-table ranking-table"><thead><tr><th>Código</th><th>Imóvel</th><th>Responsável</th><th>Status</th></tr></thead><tbody>{filtered.slice(0, 5).map((item) => <tr key={item.id}><td>{item.code}</td><td>{item.property}</td><td>{item.responsible}</td><td>{item.status}</td></tr>)}</tbody></table></div></article><article className="panel analysis-insight"><span className="insight-icon"><Icon name="chart" size={23} /></span><h3>Indicador atualizado</h3><p>{completed} de {total} triagens filtradas estão concluídas. Use os filtros acima para comparar cidades e tipos de execução.</p><Link className="button button--outline" href="/relatorios">Ver relatórios <Icon name="arrowRight" size={15} /></Link></article></section>
  </>;
}
